### ISSUE TITLE
Supertypes of the following classes cannot be resolved.

### ISSUE THREAD

**Issue by Kadanza** [Shopify/livedata-ktx#12]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

class com.shopify.livedataktx.SupportMediatorLiveData, unresolved supertypes: androidx.lifecycle.MediatorLiveData

What is wrong?

**Comment by henrytao-me** [comment]
Could it be something related to your gradle dependencies setup? Can you share your build.gradle?

**Comment by Kadanza** [comment]
it's here
https://github.com/Kadanza/TestModules/blob/master/base/build.gradle

https://github.com/Kadanza/TestModules

**Comment by henrytao-me** [comment]
Hi @Kadanza 

I found the issue. LiveData 2.x is under different package name `androidx.lifecycle` while the 1.x is under `android.arch.lifecycle`. That is why the extension does not work. 

I log a ticket here to upgrade LiveDataKtx to support 2.x https://github.com/Shopify/livedata-ktx/issues/13. Thanks for your feedback. New version will be pushed shortly.

**Comment by Kadanza** [comment]
Thanks)

**Comment by henrytao-me** [comment]
@Kadanza 

Please try `implementation "com.shopify:livedata-ktx:2.0.0"`. From now on, LiveDataKtx 1.x is for LiveData 1.x. LiveDataKtx 2.x is for LiveData 2.x. 

Let me know if it works for you.

**Comment by aliboi** [comment]
apply plugin: 'com.android.feature'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation project(':base')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    
}


> Could it be something related to your gradle dependencies setup? Can you share your build.gradle?

build.gradle shared.

Kindly help please
