### ISSUE TITLE
remove @Suppress("DEPRECATION")

### ISSUE THREAD

**Issue by TakuSemba** [Shopify/livedata-ktx#17]
Hi, I want to remove the @Suppress("DEPRECATION") at LiveData.kt

I want to know why deprication of SupportMediatorLiveData#observe() is suppressed.

I think It's better that showing an depricated warning when using the methods above, because `Removable` has a method `removeObserver()` to remove an observer but that does not work since removable has a different observer from the one actually observing.

And I also want to confirm that the reason you are depricating the method is what I mentioned above.

thank you in advance.

**Comment by henrytao-me** [comment]
Thanks for your feedback. I will look closer to this and make some improvements.

**Comment by henrytao-me** [comment]
All `observe` extensions are now removed in latest implementation. We restructure how the library works to focus on Kotlin friendly. Thanks for your feedback.
