### ISSUE TITLE
different between versions 3.0.0 and 2.0.2

### ISSUE THREAD

**Issue by Kadanza** [Shopify/livedata-ktx#23]
Hi 
- **1)** what  improvement has version 3.0.0?

- **2)** why need  MutableLiveDataKtx instead MutableLiveData? 

- **3)** In version 2.0 we has great extension observe without Observer

livedata.observe(this) {it ->

}

In version 3.0 observe  without Observer  is gone =(
We have now only ugly

.observe(lifecycleOwner, Observer { result ->
   
  })

- **4)**

In version 2.0  I has unpleasant  bug  in android studio, 
My breakpoint is skipped by android studio in extension observe, but code in worked

livedata.observe(this) {it ->
// here breakpoint
}

but  common way work fine
.observe(lifecycleOwner, Observer { result ->
    // result is non-null and always true
  })

**Comment by Kadanza** [comment]
point 4 : 
some device have this error (with old api Android)

Nexus 6p - Android 8.1 doesn't have this mistake

**Comment by henrytao-me** [comment]
Hi @Kadanza, I missed your original message. Thanks for reaching out. Hopefully, I can address some of your questions below:

> 1) what improvement has version 3.0.0?
> 2) why need MutableLiveDataKtx instead MutableLiveData?

As listed in the README, v3 focuses on Kotlin friendly, preserve immutability, and extensibility. For instance, you still can set null value for a non-null LiveData which can cause NPE at runtime. Compiler should be able to prevent it. 

```
// Allow to set null value to LiveData
val liveData = MutableLiveData<Boolean>()
liveData.value = null

// LiveDataKtx doesn't allow to null value
val liveData = MutableLiveDataKtx<Boolean>()
liveData.value = null // doesn't allow

// Set nullable in LiveDataKtx
val liveData = MutableLiveDataKtx<Boolean?>()
liveData.value = null
```

> 3) In version 2.0 we has great extension observe without Observer

There is tradeoffs for the approach. Kotlin lambda generates different object down to Java layer which make harder to remove the observer later on.

> 4) In version 2.0 I has unpleasant bug in android studio

I haven't encountered this issue. I can take a look later.

**Comment by Kadanza** [comment]
point 3 :  are you not recommend use version 2 because of problem with memory?

I use version 2 widely

**Comment by henrytao-me** [comment]
If you use v2.0.2, `removeObserver` should work properly as we had a fix for it  https://github.com/Shopify/livedata-ktx/releases/tag/v2.0.2.

**Comment by henrytao-me** [comment]
Let us know if you have any other concerns. I will close this issue for now. Feel free to reopen if needed.
