### ISSUE TITLE
Unnecessary Nullable types

### ISSUE THREAD

**Issue by NickEcho** [Shopify/livedata-ktx#3]
First of all, nice work on this. I started doing something similar and came across your work.

I have some questions about some of your implementation details.

I noticed you use a nullable value in `MediatorObserver`:
https://github.com/henrytao-me/livedata-ktx/blob/bebbc7c3d18702d0e074e0643895d80d55d8fe29/livedata-ktx/src/main/java/me/henrytao/livedataktx/LiveData.kt#L148

I don't think this is necessary. My guess is you did this because of this line:
https://github.com/henrytao-me/livedata-ktx/blob/bebbc7c3d18702d0e074e0643895d80d55d8fe29/livedata-ktx/src/main/java/me/henrytao/livedataktx/LiveData.kt#L159

The compiler would otherwise complain because of the `Observer` interface function argument is annotated with `@NonNull`. Because this is coming from java this is needed. Seeing you are using Kotlin here we could just cast to `IN` (in this case). Like this:

`mediator.addSource(source, Observer { observer.run(source, mediator, it as IN) })`

We can do this because the type we pas in from Kotlin is already nullable so you don't have to check for non-null in the calling code.

this replaces the following:
```Kotlin
val liveData = MutableLiveData<Int>
val mapped = liveData.map { it?.let{ it.toString() } }
```

with:
```Kotlin
val liveData = MutableLiveData<Int>
val mapped = liveData.map { it.toString() }
```

This should still work fine if you have nullable types in Kotlin:
```Kotlin
val liveData = MutableLiveData<Int?>
// val mapped = liveData.map { it.toString() } <-- this wouldn't work
val mapped = liveData.map { it?.let{ it.toString() } }
```

What's your thoughts?

Edit:
I've went a head and created a PR with these changes for you to take a look at.

**Comment by henrytao-me** [comment]
Thanks for creating issue. I am taking a look now. Not sure why I didn't get email notification from github.

**Comment by henrytao-me** [comment]
My concern is that LiveData is written in Java, there is no differences between these code: 
```kotlin
val liveData1: LiveData<String> = MutableLiveData()
var value1: String? = liveData1.value

val liveData2: LiveData<String?> = MutableLiveData()
var value2: String? = liveData2.value
```
`value` from livedata is optional in both cases, even without using this library. 

So, if we resolve nullability by forcing type like `LiveData<String>` and `LiveData<String?>`, we will introduce miss usage later on. Ex: people who are using original MutableLiveData<String> expects value as nullable but it becomes non-null after adding this library. 

My best practices on using this library is adding `.nonNull()` before doing `.observe()`. I am afraid that we should stick with it for now until original LiveData switches to Kotlin.

**Comment by henrytao-me** [comment]
Thanks @NickEcho. Great suggestion. I would prefer to keep this library in-sync with Android Framework for now and revisit it every time architecture components has new version. I hope it will release a kotlin version of LiveData in the future.

**Comment by henrytao-me** [comment]
Thanks @NickEcho for your great suggestion. It makes sense now to focus on Kotlin friendly version of LiveData after LiveData moved to `androidx` and version 2.0.0 is released. We pushed version 3.0.0 with major refactors, including your suggestion.
